name: Build and Deploy game-2048 to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gcp-atif
  GKE_CLUSTER: google-cluster    # Add your cluster name here.
  GKE_ZONE: asia-south2-a   # Add your cluster zone here.
  DEPLOYMENT_NAME: game-2048 # Add your deployment name here.
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

   
    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_PRIVATE_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
    - name: Print image tag
      run: echo $GITHUB_RUN_ID
   
    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Checkout repository
      uses: actions/checkout@v2
 
#    - name: Login to GitHub Container Registry
 #     uses: docker/login-action@v1
 #     with:
 #       registry: ghcr.io
  #      username: ${{ github.actor }}
  #      password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
     # Push the Docker image to Google Container Registry 
    - name: Build the hello-docker Docker image
      run: |
       docker build . --tag ghcr.io/gcp-atif/game-2048:$GITHUB_RUN_ID
       docker run ghcr.io/gcp-atif/game-2048:$GITHUB_RUN_ID
       docker push ghcr.io/gcp-atif/game-2048:$GITHUB_RUN_ID
        
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide  
        
        #test
