name: Build and Deploy game-2048 to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: gcp-atif
  GKE_CLUSTER: google-cluster    # Add your cluster name here.
  GKE_ZONE: asia-south2-a   # Add your cluster zone here.
  DEPLOYMENT_NAME: game-2048 # Add your deployment name here.
  IMAGE: static-site

jobs:
  build-and-push-to-gcr-workload-identity:
    name: Build & push - with workload identity
    runs-on: ubuntu-latest
    permissions: # <- this section is needed for workload identity
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Print image tag
      run: echo $GITHUB_RUN_ID

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet


    # Setup gcloud CLI
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v0
      with:
          workload_identity_provider: //iam.googleapis.com/projects/126557959099/locations/global/workloadIdentityPools/atif-pool/attribute.repository/2048-Game-GCP-Kubernetes
          service_account: googel-container-registry@gcp-atif.iam.gserviceaccount.com

    - uses: actions/checkout@v3
      name: Building and pushing the image

    -  uses: RafikFarhad/push-to-gcr-github-action@v5-beta
       with:
          gcloud_service_key: "${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}"
          registry: gcr.io
          project_id: gcp-atif
          image_name: game-2048
          image_tag: ${{ github.sha }}
          dockerfile: Dockerfile
         # context: ./test
        #  target: build
    - run: |
       docker build -t gcr.io/gcp-atif/game-2048:${{ github.sha }} . 
       docker push gcr.io/gcp-atif/game-2048:${{ github.sha }}
       
              
 #   - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
  #    with:
   #       # gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text || not needed if you use google-github-actions/auth
    #       registry: gcr.io
     #      project_id: gcp-atif
      #     image_name: game-2048
       #    image_tag: ${{ github.sha }}
        #   dockerfile: Dockerfile
         #  #context: ./docker-context.md


    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
