name: Build and Deploy game-2048 to GKE

on:
  push:
    branches:
      - main
jobs:
  build-and-push-to-gcr-workload-identity:
    name: Build & push - with workload identity
    runs-on: ubuntu-latest
    permissions: # <- this section is needed for workload identity
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t gcr.io/gcp-atif/game-2048:${{ github.sha }} .

      # Configure Workload Identity Federation for Google Cloud
      - id: auth
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: projects/126557959099/locations/global/workloadIdentityPools/atif-pool
          service_account: googel-container-registry@gcp-atif.iam.gserviceaccount.com
          create_credentials_file: true

      # Setup gcloud CLI
      - name: Setup Google Cloud SDK
        uses: mathieu-bour/setup-gcloud@1.3.1

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: 'Set up docker to authenticate via gcloud command-line tool'
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud auth configure-docker

      - name: Push Docker image to Google Container registry
        run: |
          docker push gcr.io/gcp-atif/game-2048:${{ github.sha }}

      - name: Set up Kustomize
        run: |-
         curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
         chmod u+x ./kustomize
    
    # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
         ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
         ./kustomize build . | kubectl apply -f -
         kubectl rollout status deployment/$DEPLOYMENT_NAME
         kubectl get services -o wide  
        
        #test4
